### ISSUE TITLE
The Twilight Forest has failed to load correctly with other mods

### ISSUE THREAD

**Issue by WKyouka** [TeamTwilight/twilightforest#1098]
Forge version: 1.16.5-36.0.42
Twilight Forest version: (this is the build number)：1.16.5-4.0.434

Exception message: java.lang.NoSuchMethodError: net.minecraft.block.WoodType.create(Ljava/lang/String;)Lnet/minecraft/block/WoodType;

Stacktrace:
	at twilightforest.block.TFBlocks.<clinit>(TFBlocks.java:273) ~[?:?] {re:classloading}
	at twilightforest.TwilightForestMod.<init>(TwilightForestMod.java:108) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
	at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?] {}

**Comment by GizmoTheMoonPig** [comment]
Please update forge to a newer version. I would suggest using the recommended version. A newer version added support for signs, that's why it's not working. (reminder to self to bump minimum forge)
