### ISSUE TITLE
Crashes and I don't know why

### ISSUE THREAD

**Issue by eenkeermilo** [TeamTwilight/twilightforest#1130]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 5/17/21 8:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: twilightforest/block/BlockTFMagicLogSpecial
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: twilightforest/block/BlockTFMagicLogSpecial
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: twilightforest.block.BlockTFMagicLogSpecial
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.jeid.modsupport.json:MixinBlockTFMagicLogSpecial] from phase [DEFAULT] in config [mixins.jeid.modsupport.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 48 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "sendChangedBiome" was not located in target class twilightforest/block/BlockTFMagicLogSpecial
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:459)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:433)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 425280536 bytes (405 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                          | Signature                                |
	|:----- |:------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft           | 1.12.2            | minecraft.jar                                   | None                                     |
	| LC    | mcp                 | 9.42              | minecraft.jar                                   | None                                     |
	| LC    | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore       |                   | minecraft.jar                                   | None                                     |
	| LC    | lesslag             | 1.0               | minecraft.jar                                   | None                                     |
	| LC    | securitycraft       | v1.8.21           | [1.12.2]+SecurityCraft+v1.8.21.jar              | None                                     |
	| LC    | aiimprovements      | 0.0.1.3           | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
	| LC    | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LC    | jei                 | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                       | None                                     |
	| LE    | twilightforest      | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| L     | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| L     | galacticraftcore    | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar           | None                                     |
	| L     | galacticraftplanets | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None                                     |
	| L     | asmodeuscore        | 0.0.25            | AsmodeusCore-1.12.2-0.0.25.jar                  | None                                     |
	| L     | base                | 3.13.0            | base-1.12.2-3.13.0.jar                          | None                                     |
	| L     | carryon             | 1.12.3            | carryon-1.12.2-1.12.4.16.jar                    | None                                     |
	| L     | cavern              | 2.3.1             | Cavern_1.12.2-v2.3.1.jar                        | None                                     |
	| L     | clumps              | 3.1.2             | Clumps-3.1.2.jar                                | None                                     |
	| L     | cyclicmagic         | 1.20.8            | Cyclic-1.12.2-1.20.9.jar                        | None                                     |
	| L     | dfheroesexpansion   | 1.3               | DFHeroesExpansion 1.3(non restricted forge).jar | None                                     |
	| L     | dungeonsmod         | 1.12.2-1.0.6      | DungeonsMod-1.12.2-1.0.6.jar                    | None                                     |
	| L     | extrautils2         | 1.0               | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| L     | galaxyspace         | 2.0.16            | GalaxySpace-1.12.2-2.0.16.jar                   | None                                     |
	| L     | ironman             | Beta-1.12.2-1.2.6 | IronMan-1.12.2-Beta-1.12.2-1.2.6.jar            | None                                     |
	| L     | speedsterheroes     | 1.12.2-2.2.1      | SpeedsterHeroes-1.12.2-2.2.1.jar                | None                                     |
	| L     | lucraftcore         | 1.12.2-2.4.14     | LucraftCore-1.12.2-2.4.14.jar                   | None                                     |
	| L     | heroesexpansion     | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar                | None                                     |
	| L     | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| L     | llibrary            | 1.7.20            | llibrary-1.7.20-1.12.2.jar                      | None                                     |
	| L     | iceandfire          | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                     | None                                     |
	| L     | infinity            | 1.12              | infinity-1.12.jar                               | None                                     |
	| L     | jeid                | 1.0.2-26          | JustEnoughIDs-1.0.2-26.jar                      | None                                     |
	| L     | memeinabottle       | 3.0.0             | MemeInABottle-1.12.X-3.0.0.jar                  | None                                     |
	| L     | stevekung's_lib     | 1.1.10            | SteveKunG's-Lib-1.12.2-1.1.10.jar               | None                                     |
	| L     | moreplanets         | 2.2.1             | More-Planets-1.12.2-2.2.1-GC280.jar             | None                                     |
	| L     | switchbow           | 1.5.8             | switchbow-1.5.8.jar                             | None                                     |
	| L     | the-fifth-world     | 0.5               | the-fifth-world-0.5.1.jar                       | None                                     |
	| L     | examplemod          | 1.0               | thejungle-1.2008.1222.jar                       | None                                     |
	| L     | thejungle           | 1.2008.1222       | thejungle-1.2008.1222.jar                       | None                                     |
	| L     | travelersbackpack   | 1.0.34            | TravelersBackpack-1.12.2-1.0.34.jar             | None                                     |
	| L     | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| L     | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-16.1.12' Renderer: 'Intel(R) Iris(TM) Plus Graphics OpenGL Engine'
Steps to reproduce:
1. 

What I expected to happen:
to just load
What happened instead:
it crashed

**Comment by Tamaized** [comment]
Duplicate #685
