### ISSUE TITLE
TF world generation crashed server (a single server tick took 60.00 seconds)

### ISSUE THREAD

**Issue by Spuckwaffel** [TeamTwilight/twilightforest#1221]
Forge version: 
Twilight Forest version: 3.8.689
Link to crash log: https://gist.github.com/Spuckwaffel/fcc133cd574216b1d992250de31a908b

Steps to reproduce:
1. go to the twilight forest
2. walk around

What I expected to happen:
nothing, normal gameplay

What happened instead:
server crash (a tick took longer than 60 seconds -> server crashes)
`(ServerHangWatchdog detected that a single server tick took 60.00 seconds)`

(head stacktrace here pasted)
-- Head --
```
Stacktrace:
	at twilightforest.world.feature.TFGenVines.func_180709_b(TFGenVines.java:34)
	at twilightforest.biomes.TFBiomeSwamp.func_180624_a(TFBiomeSwamp.java:99)
	at twilightforest.world.ChunkGeneratorTwilightForest.func_185931_b(ChunkGeneratorTwilightForest.java:474)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

**Comment by Tamaized** [comment]
You're extremely outdated, but do you have the Recurrent Complex mod or similar world gen mods? Those are known to cause really bad cascading world gen with TF which hangs the game.

**Comment by Sooperfish** [comment]
I have this on 4.0546 too, playing All The Mods 6.
