### ISSUE TITLE
"Ticking Block entity" after planting magic beans on the top of an existing vine.

### ISSUE THREAD

**Issue by DiscoDude96** [TeamTwilight/twilightforest#1604]
### Forge Version

43.0.7

### Twilight Forest Version

1.19

### Crash Report (if applicable)

The game crashed whilst ticking block entity Error: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} to 0 on Block{twilightforest:beanstalk_leaves}, it is not an allowed value

### Steps to Reproduce

1. Plant the vine
2. Doesn't lead to cottage?
3. Become impatient and just place another magic beans.
Congrats dumbass was it worth it?
Owners please do not reproduce this it actually stops the game from loading it ruins your world.

### What You Expected

To play the game normally

### What Happened Instead

Crash aww man

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Post the entire crash log please, not just a snippet.

**Comment by DiscoDude96** [comment]
ok

**Comment by DiscoDude96** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-08-19 16:44:32
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} to 0 on Block{twilightforest:beanstalk_leaves}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.tryToPlaceLeaves(GrowingBeanstalkBlockEntity.java:185) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.placeLeaves(GrowingBeanstalkBlockEntity.java:153) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.tick(GrowingBeanstalkBlockEntity.java:123) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.tryToPlaceLeaves(GrowingBeanstalkBlockEntity.java:185) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.placeLeaves(GrowingBeanstalkBlockEntity.java:153) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at twilightforest.block.entity.GrowingBeanstalkBlockEntity.tick(GrowingBeanstalkBlockEntity.java:123) ~[twilightforest-1.19-4.2.1381-universal.jar%23159!/:4.2.1381] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: twilightforest:beanstalk_grower // twilightforest.block.entity.GrowingBeanstalkBlockEntity
	Block: Block{twilightforest:beanstalk_grower}
	Block location: World: (24,178,-74), Section: (at 8,2,6 in 1,11,-5; chunk contains blocks 16,-32,-80 to 31,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-32,-512 to 511,255,-1)
	Block: Block{twilightforest:beanstalk_grower}
	Block location: World: (24,178,-74), Section: (at 8,2,6 in 1,11,-5; chunk contains blocks 16,-32,-80 to 31,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-32,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Disco_Dude96'/161, l='ServerLevel[1.19.2 Alpha Testing World]', x=25.63, y=189.00, z=-81.73]]
	Chunk stats: 2025
	Level dimension: twilightforest:twilight_forest
	Derived: true
	Level spawn location: World: (-32,74,0), Section: (at 0,10,0 in -2,4,0; chunk contains blocks -32,-32,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-32,0 to -1,255,511)
	Level time: 1661955 game time, 1849156 day time
	Level name: 1.19.2 Alpha Testing World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2030950720 bytes (1936 MiB) / 4697620480 bytes (4480 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 19656.21
	Virtual memory used (MB): 13432.07
	Swap memory total (MB): 3328.00
	Swap memory used (MB): 192.34
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Disco_Dude96'/161, l='ServerLevel[1.19.2 Alpha Testing World]', x=25.63, y=189.00, z=-81.73]]
	Data Packs: vanilla, mod:terrablender, mod:moonlight (incompatible), mod:structurize, mod:worldedit (incompatible), mod:byg (incompatible), mod:domum_ornamentum, mod:forge, mod:twilightforest (incompatible), mod:blockui, mod:multipiston, mod:xaerominimap, mod:croptopia (incompatible), mod:xaeroworldmap, mod:blue_skies, mod:structure_gel, mod:jei (incompatible), mod:appleskin, mod:aquaculture, mod:supplementaries (incompatible), Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.2-forge-43.0.7
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraBlender-forge-1.19.2-2.0.1.125.jar           |TerraBlender                  |terrablender                  |2.0.1.125           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19-2.0.14.jar                         |Moonlight Library             |moonlight                     |1.19-2.0.15         |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.19.1-1.3.19.jar                      |Blue Skies                    |blue_skies                    |1.3.19              |DONE      |Manifest: NOSIGNATURE
		structurize-1.19.1-1.0.423-ALPHA.jar              |Structurize                   |structurize                   |1.19.1-1.0.423-ALPHA|DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.2.0.246.jar                   |Just Enough Items             |jei                           |11.2.0.246          |DONE      |Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.7.jar  |Oh The Biomes You'll Go       |byg                           |2.0.0.7             |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.59-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.59-ALPHA   |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.0.7-universal.jar                 |Forge                         |forge                         |43.0.7              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.19-2.4.5.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.5          |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19-4.2.1381-universal.jar        |The Twilight Forest           |twilightforest                |4.2.1381            |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.0.13.jar                 |Supplementaries               |supplementaries               |1.19.2-2.0.13       |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.59-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.59-ALPHA   |DONE      |Manifest: NOSIGNATURE
		multi-piston-1.19-1.2.16-ALPHA.jar                |Multi-Piston                  |multipiston                   |1.19-1.2.16-ALPHA   |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.13.0_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.13.0             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.0.8.jar                  |Croptopia                     |croptopia                     |2.0.8               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.26.2_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.26.2              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.19.1-2.5.6.jar                    |Structure Gel API             |structure_gel                 |2.5.6               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 46ab6a9c-666c-42fc-8797-aed3ec28f02b
	FML: 43.0
	Forge: net.minecraftforge:43.0.7

**Comment by DiscoDude96** [comment]
Hopefully this doesn't give out too much info

**Comment by GizmoTheMoonPig** [comment]
although I can't directly reproduce this after trying for a bit, I still added a catch for it. Thanks for reporting!

**Comment by DiscoDude96** [comment]
> although I can't directly reproduce this after trying for a bit, I still added a catch for it. Thanks for reporting!
Did you do it at near hight limit?

**Comment by DiscoDude96** [comment]
Nevermind I fixed it but thanks for your time!
