### ISSUE TITLE
Crash Kill 'Stable Ice Core'

### ISSUE THREAD

**Issue by Misoss** [TeamTwilight/twilightforest#317]
Server Crash when a 'Stable Ice Core' explodes
**Versions :**
Minecraft 1.12.2
Forge 14.23.0.2512
twilightforest-1.12.2-3.1.128-universal

**Error Logs :**
`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  LoadingPlugin (Quark-r1.3-111.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 11/1/17 12:07 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_193350_e()I
        at twilightforest.entity.EntityTFIceExploder.getClosestDyeColor(EntityTFIceExploder.java:179)
        at twilightforest.entity.EntityTFIceExploder.transformBlock(EntityTFIceExploder.java:146)
        at twilightforest.entity.EntityTFIceExploder.transformBlocks(EntityTFIceExploder.java:127)
        at twilightforest.entity.EntityTFIceExploder.func_70609_aI(EntityTFIceExploder.java:104)
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
        at net.minecraft.world.World.func_72866_a(World.java:1986)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
        at net.minecraft.world.World.func_72870_g(World.java:1948)
        at net.minecraft.world.World.func_72939_s(World.java:1755)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at twilightforest.entity.EntityTFIceExploder.getClosestDyeColor(EntityTFIceExploder.java:179)
        at twilightforest.entity.EntityTFIceExploder.transformBlock(EntityTFIceExploder.java:146)
        at twilightforest.entity.EntityTFIceExploder.transformBlocks(EntityTFIceExploder.java:127)
        at twilightforest.entity.EntityTFIceExploder.func_70609_aI(EntityTFIceExploder.java:104)
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
        at net.minecraft.world.World.func_72866_a(World.java:1986)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
        at net.minecraft.world.World.func_72870_g(World.java:1948)

-- Entity being ticked --
Details:
        Entity Type: twilightforest:unstable_ice_core (twilightforest.entity.EntityTFIceExploder)
        Entity ID: 562
        Entity Name: Unstable Ice Core
        Entity's Exact location: -5879.60, 143.00, 16934.40
        Entity's Block location: World: (-5880,143,16934), Chunk: (at 8,8,6 in -368,1058; contains blocks -5888,0,16928 to -5873,255,16943), Region: (-12,33; contains chunks -384,1056 to -$
        Entity's Momentum: 0.00, -0.08, 0.00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1755)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
        Level name: world_mods_1122_v2
        All players: 1 total; [EntityPlayerMP['Misoss'/551, l='world_mods_1122_v2', x=-5875.32, y=143.00, z=16936.97]]
        Chunk stats: ServerChunkCache: 446 Drop: 0
        Level seed: -1834353918008016421
        Level generator: ID 00 - default, ver 1. Features enabled: false
        Level generator options:
        Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 0 game time, 0 day time
        Level dimension: 0
        Level storage version: 0x00000 - Unknown?
        Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

`

**Comment by Tamaized** [comment]
This was fixed already, you're on an outdated version. Update.
