### ISSUE TITLE
[DW20 1.12.2 1.4.0] - No progression or advancements

### ISSUE THREAD

**Issue by jinks** [TeamTwilight/twilightforest#380]
Forge version: 14.23.1.2566
Twilight Forest version: 1.12.2-3.5.263-universal

I get no progression messages or unlocks at all (killed 2 nagas so far) and there is no advancement tab for TF at all.

Error message looks like the whole of TF advancements is missing completely:
```
[03:24:11] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:233) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_194220_a(PlayerAdvancements.java:360) ~[np.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194027_a(NetHandlerPlayServer.java:445) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:50) ~[lu.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:11) ~[lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 3 more
```

Game is single player, but has been open to LAN before (not while being in the TF, though). I have not been to the TF in previous versions of the pack.

Is this related to #344?

**Comment by Andromander** [comment]
It may be caused by being in LAN, but this is occurring in Single Player I assume? Are there other mods installed or it is only Twilight Forest?

Also, can you try rebooting Minecraft and seeing what happens? The error doesn't look like it is pointing specifically to Twilight Forest.

**Comment by jinks** [comment]
> It may be caused by being in LAN, but this is occurring in Single Player I assume? 

It is. The world has only been open to LAN once in the past to test my SO's client.

> Are there other mods installed or it is only Twilight Forest?

Loads. As the title says, current DW20 pack.

> Also, can you try rebooting Minecraft and seeing what happens?

A full restart of Minecraft did indeed solve it. - As soon as I re-entered the portal I got the "Twilight Forest" advancement and the tab appeared in the advancements "book".

By the looks of it, since the first advancement didn't trigger the tab for TF never got created and thus MC threw a NPE each time TF tried to activate further advancements.
I could reliably trigger the above error by throwing a naga trophy on the ground and picking it up again.

Feel free to close this one, since I probably can't replicate it now any more.
