### ISSUE TITLE
Game crashes when animal enters portal

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#43]
Happened with a cow. (If unable to reproduce, try: Baby Cow, Burning Cow, Burning Baby Cow)
World is unable to be load afterwards. Game immediately crashes.

```
[net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.11.2-0.1.0.4.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/19/17 2:01 AM
Description: Colliding entity with block

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at twilightforest.block.BlockTFPortal.changeDimension(BlockTFPortal.java:346)
	at twilightforest.block.BlockTFPortal.func_180634_a(BlockTFPortal.java:281)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1024)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:945)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1866)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2289)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at twilightforest.block.BlockTFPortal.changeDimension(BlockTFPortal.java:346)
	at twilightforest.block.BlockTFPortal.func_180634_a(BlockTFPortal.java:281)

-- Block being collided with --
Details:
	Block: twilightforest:twilight_portal
	Block location: World: (-295,62,458), Chunk: (at 9,3,10 in -19,28; contains blocks -304,0,448 to -289,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1024)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:cow (net.minecraft.entity.passive.EntityCow)
	Entity ID: 101
	Entity Name: Kuh
	Entity's Exact location: -295.00, 63.50, 459.00
	Entity's Block location: World: (-295,63,459), Chunk: (at 9,3,11 in -19,28; contains blocks -304,0,448 to -289,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:945)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1866)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2289)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

-- Entity being ticked --
Details:
	Entity Type: minecraft:cow (net.minecraft.entity.passive.EntityCow)
	Entity ID: 101
	Entity Name: Kuh
	Entity's Exact location: -295.00, 63.50, 459.00
	Entity's Block location: World: (-295,63,459), Chunk: (at 9,3,11 in -19,28; contains blocks -304,0,448 to -289,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: TW Forest Alpha Test
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 701 Drop: 0
	Level seed: -1150869130011381476
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-270,64,452), Chunk: (at 2,4,4 in -17,28; contains blocks -272,0,448 to -257,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 204290 game time, 221786 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 2218 (now: true), thunder time: 62084 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 260013160 bytes (247 MB) / 564355072 bytes (538 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	ctm{MC1.11.2-0.1.0.4} [CTM] (CTM-MC1.11.2-0.1.0.4.jar) 
	UCHIJAAAA	twilightforest{2.3.8dev} [The Twilight Forest] (twilightforest-1.11.2-2.4.0.5-universal.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.11.2-0.1.0.4.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by williewillus** [comment]
fixed by 615bba7 (build 7+)
