### ISSUE TITLE
Crash upon entering Twilight Forest

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#58]
Crash occured after world finished loading in.

Edit: Posted wrong log, correct one below.

**Comment by Matti-Koopa** [comment]
Happens every time upon loading safe file. Immediate crash.

**Comment by Tamaized** [comment]
it's the same error as #43 have you tried using the latest build?

**Comment by Matti-Koopa** [comment]
I'm on build 23.

**Comment by Tamaized** [comment]
I think you posted the wrong log ;) even the date is the same as the other

**Comment by Matti-Koopa** [comment]
My apology.

```
	[net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.11.2-0.1.0.4.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 6/19/17 10:54 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=color, clazz=class net.minecraft.item.EnumDyeColor, values=[pink, blue, yellow, purple]} to null on block twilightforest:castle_rune_brick, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at twilightforest.structures.lichtower.ComponentTFTowerWing.makeGlyphBranches(ComponentTFTowerWing.java:2346)
	at twilightforest.structures.finalcastle.ComponentTFFinalCastleMazeTower13.func_74875_a(ComponentTFFinalCastleMazeTower13.java:485)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at twilightforest.world.ChunkGeneratorTwilightForest.func_185931_b(ChunkGeneratorTwilightForest.java:860)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at twilightforest.structures.lichtower.ComponentTFTowerWing.makeGlyphBranches(ComponentTFTowerWing.java:2346)
	at twilightforest.structures.finalcastle.ComponentTFFinalCastleMazeTower13.func_74875_a(ComponentTFFinalCastleMazeTower13.java:485)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at twilightforest.world.ChunkGeneratorTwilightForest.func_185931_b(ChunkGeneratorTwilightForest.java:860)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
	Level name: TW Forest Alpha Test
	All players: 1 total; [EntityPlayerMP['MattiKoopa'/157, l='TW Forest Alpha Test', x=-297.46, y=34.00, z=448.85]]
	Chunk stats: ServerChunkCache: 733 Drop: 0
	Level seed: -1150869130011381476
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 317366640 bytes (302 MB) / 832823296 bytes (794 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 37
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	ctm{MC1.11.2-0.1.0.4} [CTM] (CTM-MC1.11.2-0.1.0.4.jar) 
	UCHIJAAAA	twilightforest{2.3.8dev} [The Twilight Forest] (twilightforest-1.11.2-2.4.0.23-universal.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.11.2-0.1.0.4.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MattiKoopa'/157, l='TW Forest Alpha Test', x=-297.46, y=34.00, z=448.85]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```
