### ISSUE TITLE
NPE when attempting to spawn naga

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#7]
java.lang.NullPointerException: Ticking block entity
    	at twilightforest.tileentity.TileEntityTFBossSpawner.spawnMyBoss(TileEntityTFBossSpawner.java:76)
    	at twilightforest.tileentity.TileEntityTFBossSpawner.update(TileEntityTFBossSpawner.java:54)
    	at net.minecraft.world.World.updateEntities(World.java:1952)
    	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:647)
    	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:784)
    	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:688)
    	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:537)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by AtomicBlom** [comment]
There's a good chance that this was fixed in https://github.com/TeamTwilight/twilightforest/commit/82a169d52d6488b051f00484d7a7ee04989e2ff6

Creatures were registered with "twilightforest." as a prefix, but then looking them up using "TwilightForest."
