### ISSUE TITLE
在新版本在Mohist服务器里面报错

### ISSUE THREAD

**Issue by DnoYT** [TeamTwilight/twilightforest#856]
Forge version: 
Twilight Forest version: 1.12.2 - 3.10.1013
Link to crash log:22:27:24] [Server thread/WARN] [net.minecraft.tileentity.TileEntity]: Skipping BlockEntity with id twilightforest:firefly
[22:27:24] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to create block entity twilightforest:firefly
java.lang.InstantiationException: twilightforest.entity.passive.EntityTFMobileFirefly
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:114) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:505) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102) [ChunkIOProvider.class:0668f70]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:174) [ChunkIOExecutor.class:0668f70]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:870) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodException: twilightforest.entity.passive.EntityTFMobileFirefly.<init>()
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_202]
	... 10 more
[22:27:24] [Server thread/ERROR] [FML]: A TileEntity twilightforest:firefly(twilightforest.entity.passive.EntityTFMobileFirefly) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.InstantiationException: twilightforest.entity.passive.EntityTFMobileFirefly
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:114) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:505) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102) [ChunkIOProvider.class:0668f70]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:174) [ChunkIOExecutor.class:0668f70]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:870) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodException: twilightforest.entity.passive.EntityTFMobileFirefly.<init>()
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_202]
	... 10 more

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

**Comment by Killer-Demon** [comment]
The Firefly entity no longer exists in the 1.16.5 version, so this issue won't apply anymore.
