### ISSUE TITLE
[1.15.2 build 64]Server crashes instantly when entering the portal

### ISSUE THREAD

**Issue by rikka0w0** [TeamTwilight/twilightforest#886]
# Forge version: 
forge-1.15.2-31.2.0
# Twilight Forest version:
#64
# Link to crash log
https://gist.github.com/rikka0w0/e23f90e6e348d747acc8628b03243440

# Steps to reproduce:
Enter the portal with
twilightforest-1.15.2-4.0.64-universal.jar

# What I expected to happen:

# What happened instead:
Crashed with log:
```
[m[1;31m[03:31:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server


java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk


	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_151] {}


	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_151] {}


	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_151] {}


	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_151] {}


	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_151] {}


	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}


	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}


	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}


	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}


	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_151] {}


	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_151] {}


	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_151] {}


	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_151] {}


	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_151] {}


Caused by: net.minecraft.crash.ReportedException: Exception generating new chunk


	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:529) ~[?:?] {re:classloading}


	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}


	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?] {re:classloading}


	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_151] {}


	... 11 more


Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 0 0


	at net.minecraft.world.gen.WorldGenRegion.func_217353_a(WorldGenRegion.java:125) ~[?:?] {re:classloading}


	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:101) ~[?:?] {re:classloading}


	at net.minecraft.world.gen.WorldGenRegion.func_212866_a_(WorldGenRegion.java:97) ~[?:?] {re:classloading}


	at net.minecraft.world.IWorldReader.func_217349_x(IWorldReader.java:93) ~[?:?] {re:classloading}


	at net.minecraft.world.gen.WorldGenRegion.func_180501_a(WorldGenRegion.java:214) ~[?:?] {re:classloading}


	at twilightforest.world.ChunkGeneratorTwilightForest.initPrimer(ChunkGeneratorTwilightForest.java:76) ~[?:?] {re:classloading}


	at twilightforest.world.ChunkGeneratorTwilightForest.func_202092_b(ChunkGeneratorTwilightForest.java:47) ~[?:?] {re:classloading}


	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B}


	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}


	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518) ~[?:?] {re:classloading}


	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}


	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?] {re:classloading}


	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_151] {}


	... 11 more
```

**Comment by Tamaized** [comment]
Idk what you expected

**Comment by williewillus** [comment]
we're aware of this

**Comment by rikka0w0** [comment]
good lucks guys, waiting for your good news
