### ISSUE TITLE
(1.16.2 Bug) Crash upon loading a world with Optifine 1.16.2 HD U G3

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#957]
Forge version: forge-1.16.2-33.0.37
Twilight Forest version: twilightforest-1.16.2-4.0.214-universal
Optifine version: Optifine 1.16.2 HD U G3

NOTE: **This is most likely a bug on Optifine's end, however I felt the bug report should still be here as well since the crash seems to only happen with the Twilight Forest (all other mods I've tested work with Optifine).**

Launcher Crash Message: 
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: (256, 0) outside of image bounds (256, 8192)
Exit Code: -1

Full Crash Log:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/4/20 1:01 AM
Description: Unexpected error

java.lang.IllegalArgumentException: (256, 0) outside of image bounds (256, 8192)
	at net.minecraft.client.renderer.texture.NativeImage.func_195709_a(NativeImage.java:261) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.func_229259_a_(TextureAtlasSprite.java:643) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.func_229257_a_(TextureAtlasSprite.java:628) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.access$600(TextureAtlasSprite.java:589) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_94219_l(TextureAtlasSprite.java:498) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_94248_c(AtlasTexture.java:523) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_110550_d(AtlasTexture.java:639) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:214) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1408) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:930) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.37.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/521466380.call(Unknown Source) [forge-1.16.2-33.0.37.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.texture.NativeImage.func_195709_a(NativeImage.java:261)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.func_229259_a_(TextureAtlasSprite.java:643)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.func_229257_a_(TextureAtlasSprite.java:628)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite$InterpolationData.access$600(TextureAtlasSprite.java:589)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_94219_l(TextureAtlasSprite.java:498)
	at net.minecraft.client.renderer.texture.AtlasTexture.func_94248_c(AtlasTexture.java:523)
	at net.minecraft.client.renderer.texture.AtlasTexture.func_110550_d(AtlasTexture.java:639)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:214)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['SeaOfPixels'/224, l='ClientLevel', x=-793.65, y=48.00, z=-92.35]]
	Chunk stats: Client Chunk Cache: 625, 122
	Level dimension: twilightforest:twilightforest
	Level spawn location: World: (-237,74,28), Chunk: (at 3,4,12 in -15,1; contains blocks -240,0,16 to -225,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 60036 game time, 60036 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:605)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/521466380.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1991878704 bytes (1899 MB) / 3288334336 bytes (3136 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.2_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.37.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.37
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.37-client.jar Minecraft {minecraft@1.16.2 DONE}
		forge-1.16.2-33.0.37-universal.jar Forge {forge@33.0.37 DONE}
		twilightforest-1.16.2-4.0.214-universal.jar The Twilight Forest {twilightforest@NONE DONE}
	Launched Version: 1.16.2-forge-33.0.37
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.8190, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources (incompatible), vanilla, file/NewDefault+v1.34[MC1.16.2+].zip, file/MinecraftDungeonsSounds[MC1.16.2+].zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.2_HD_U_G3
	OptiFine Build: 20200829-104659
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8190
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by Hubry** [comment]
You haven't attached any crash reports here...

**Comment by Andromander** [comment]
Closing as this is an Optifine problem.
